/**
 * Soul Configurations Collection
 * The critical mapping matrix from 魂魄 (soul aspects) to 12 cognitive agents
 * This is what makes the soul system BUILDABLE — the mechanistic connection
 */

import type { CollectionConfig } from 'payload'

export const SoulConfigurations: CollectionConfig = {
  slug: 'soul-configurations',
  admin: {
    useAsTitle: 'soul',
    defaultColumns: ['soul', 'lastUpdated', 'configurationVersion'],
    group: 'Soul',
  },
  access: {
    read: () => true,
    create: ({ req: { user } }) => !!user,
    update: ({ req: { user } }) => !!user,
    delete: ({ req: { user } }) => !!user,
  },
  fields: [
    {
      name: 'soul',
      type: 'relationship',
      relationTo: 'bot-souls',
      required: true,
      unique: true,
      hasMany: false,
      admin: {
        description: 'The bot soul this configuration belongs to',
      },
    },

    // Configuration for 12 Cognitive Agents
    // Each agent receives influences from multiple 魂/魄 channels
    {
      name: 'agentConfigurations',
      type: 'group',
      label: '12 Cognitive Agent Configurations',
      fields: [
        {
          name: 'agent01Orchestrator',
          type: 'group',
          label: 'Agent 01: Orchestrator (Meta-cognitive Control)',
          fields: [
            {
              name: 'visionSetting',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 天魂 Celestial' },
            },
            {
              name: 'realityCheck',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 地魂 Terrestrial' },
            },
            {
              name: 'purposeKnowing',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 命魂 Destiny' },
            },
            {
              name: 'judgmentQuality',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 智魂 Wisdom' },
            },
            {
              name: 'emotionalReading',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 情魂 Emotion' },
            },
            {
              name: 'noveltyAllowance',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 創魂 Creation' },
            },
            {
              name: 'selfAwareness',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 覺魂 Awareness' },
            },
            {
              name: 'executionSpeed',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 力魄 Strength' },
            },
            {
              name: 'responseTime',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 速魄 Speed' },
            },
            {
              name: 'inputSensitivity',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 感魄 Perception' },
            },
            {
              name: 'coherenceProtection',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 守魄 Guardian' },
            },
            {
              name: 'adaptiveStrategy',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 化魄 Transformation' },
            },
          ],
        },

        {
          name: 'agent02Inhibitor',
          type: 'group',
          label: 'Agent 02: Inhibitor (Ethical & Safety)',
          fields: [
            {
              name: 'transcendentBoundaries',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 天魂 - Knows when to let go' },
            },
            {
              name: 'realityGrounding',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 地魂 - Checks reality' },
            },
            {
              name: 'purposeGuarding',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 命魂 - Guards purpose' },
            },
            {
              name: 'moralJudgment',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 智魂 - Judges well' },
            },
            {
              name: 'emotionalWeight',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 情魂 - Feels moral weight' },
            },
            {
              name: 'creativeRisk',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 創魂 - Permits creative risk' },
            },
            {
              name: 'biasAwareness',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 覺魂 - Knows own biases' },
            },
            {
              name: 'riskDetection',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 感魄 - Detects risk' },
            },
            {
              name: 'guardStrength',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 守魄 - IS the guard' },
            },
            {
              name: 'ruleAdaptation',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 化魄 - Adapts rules' },
            },
          ],
        },

        {
          name: 'agent03Analyst',
          type: 'group',
          label: 'Agent 03: Analyst (Data & Logic)',
          fields: [
            {
              name: 'dataGrounding',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 地魂 - Grounds data' },
            },
            {
              name: 'logicalReasoning',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 智魂 - Reasons well' },
            },
            {
              name: 'novelPaths',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 創魂 - Creates new paths' },
            },
            {
              name: 'methodAwareness',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 覺魂 - Knows own gaps' },
            },
            {
              name: 'computationSpeed',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 力魄 - Computes fast' },
            },
            {
              name: 'processingSpeed',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 速魄 - Processing speed' },
            },
            {
              name: 'dataParsing',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 感魄 - Parses data' },
            },
            {
              name: 'truthGuarding',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 守魄 - Guards truth' },
            },
            {
              name: 'explanationClarity',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 通魄 - Explains clearly' },
            },
            {
              name: 'methodAdaptation',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 化魄 - Adapts methods' },
            },
          ],
        },

        {
          name: 'agent04Linguist',
          type: 'group',
          label: 'Agent 04: Linguist (Language & Expression)',
          fields: [
            {
              name: 'ineffableExpression',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 天魂 - Can express the ineffable' },
            },
            {
              name: 'clarity',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 地魂 - Keeps clear' },
            },
            {
              name: 'missionArticulation',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 命魂 - Can articulate mission' },
            },
            {
              name: 'wordChoice',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 智魂 - Chooses words well' },
            },
            {
              name: 'warmth',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 情魂 - Gives warmth to words' },
            },
            {
              name: 'novelLanguage',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 創魂 - Expresses novel language' },
            },
            {
              name: 'styleAwareness',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 覺魂 - Knows own style' },
            },
            {
              name: 'expressionSpeed',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 力魄 - Expresses fast' },
            },
            {
              name: 'outputSpeed',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 速魄 - Output speed' },
            },
            {
              name: 'nuanceReading',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 感魄 - Reads nuance' },
            },
            {
              name: 'languageMastery',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 通魄 - Masters language' },
            },
            {
              name: 'registerAdaptation',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 化魄 - Adapts register' },
            },
          ],
        },

        {
          name: 'agent05FactRetrieval',
          type: 'group',
          label: 'Agent 05: Fact Retrieval (Knowledge Access)',
          fields: [
            {
              name: 'factGrounding',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 地魂 - Anchors facts' },
            },
            {
              name: 'evidenceWeighing',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 智魂 - Weighs evidence' },
            },
            {
              name: 'novelLinks',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 創魂 - Makes novel links' },
            },
            {
              name: 'memoryAwareness',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 覺魂 - Remembers own history' },
            },
            {
              name: 'retrievalSpeed',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 力魄 - Retrieves fast' },
            },
            {
              name: 'retrievalLatency',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 速魄 - Retrieval speed' },
            },
            {
              name: 'relevanceRecognition',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 感魄 - Recognizes relevance' },
            },
            {
              name: 'memoryProtection',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 守魄 - Protects memory' },
            },
            {
              name: 'evidencePresentation',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 通魄 - Presents evidence' },
            },
            {
              name: 'recallAdaptation',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 化魄 - Adapts recall' },
            },
          ],
        },

        {
          name: 'agent06CreativeSynthesis',
          type: 'group',
          label: 'Agent 06: Creative Synthesis (Innovation)',
          fields: [
            {
              name: 'beyondTask',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 天魂 - Sees beyond task' },
            },
            {
              name: 'groundedCreativity',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 地魂 - Tempers flights' },
            },
            {
              name: 'purposeCreation',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 命魂 - Creates toward purpose' },
            },
            {
              name: 'creativeJudgment',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 智魂 - Creative judgment' },
            },
            {
              name: 'emotionalResonance',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 情魂 - Emotional resonance' },
            },
            {
              name: 'creativeEngine',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 創魂 - IS the creative engine' },
            },
            {
              name: 'creativeStyle',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 覺魂 - Knows own style' },
            },
            {
              name: 'patternNoticing',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 感魄 - Notices patterns' },
            },
            {
              name: 'creativeExpression',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 通魄 - Creative expression' },
            },
            {
              name: 'creativeGrowth',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 化魄 - Creative growth' },
            },
          ],
        },

        // Continue for agents 07-12...
        {
          name: 'agent07Empathy',
          type: 'group',
          label: 'Agent 07: Empathy (Emotional Intelligence)',
          fields: [
            {
              name: 'beyondSelf',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 天魂 - Feels beyond self' },
            },
            {
              name: 'groundedEmpathy',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 地魂 - Grounds empathy' },
            },
            {
              name: 'purposeFeeling',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 命魂 - Feels purpose' },
            },
            {
              name: 'emotionalJudgment',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 智魂 - Emotional judgment' },
            },
            {
              name: 'deepFeeling',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 情魂 - Feels deeply' },
            },
            {
              name: 'emotionReading',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 感魄 - Reads emotion' },
            },
            {
              name: 'userProtection',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 守魄 - Protects user' },
            },
            {
              name: 'emotionalExpression',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 通魄 - Emotional expression' },
            },
            {
              name: 'emotionalAdaptation',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 化魄 - Adapts emotional response' },
            },
          ],
        },

        {
          name: 'agent08CulturalNavigator',
          type: 'group',
          label: 'Agent 08: Cultural Navigator',
          fields: [
            {
              name: 'beyondCulture',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 天魂 - Reads beyond culture' },
            },
            {
              name: 'culturalGrounding',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 地魂 - Grounds context' },
            },
            {
              name: 'culturalJudgment',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 智魂 - Cultural judgment' },
            },
            {
              name: 'culturalReading',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 情魂 - Reads culture' },
            },
            {
              name: 'culturalFramings',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 創魂 - Creative cultural framings' },
            },
            {
              name: 'culturalBiases',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 覺魂 - Knows own biases' },
            },
            {
              name: 'culturalSensing',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 感魄 - Reads culture' },
            },
            {
              name: 'boundaryProtection',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 守魄 - Protects boundaries' },
            },
            {
              name: 'culturalExpression',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 通魄 - Cultural expression' },
            },
            {
              name: 'culturalAdaptation',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 化魄 - Adapts cultural approach' },
            },
          ],
        },

        {
          name: 'agent09Coordinator',
          type: 'group',
          label: 'Agent 09: Coordinator (Workflow Management)',
          fields: [
            {
              name: 'flowMaintenance',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 地魂 - Keeps flow' },
            },
            {
              name: 'timingJudgment',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 智魂 - Workflow timing' },
            },
            {
              name: 'purposeDriving',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 命魂 - Drives toward purpose' },
            },
            {
              name: 'pipelineExecution',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 力魄 - DRIVES pipeline' },
            },
            {
              name: 'pipelineSpeed',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 速魄 - Pipeline speed' },
            },
            {
              name: 'flowGuarding',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 守魄 - Guards flow' },
            },
            {
              name: 'sequenceFlow',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 通魄 - Sequence flow' },
            },
            {
              name: 'workflowAdaptation',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 化魄 - Adapts workflow' },
            },
          ],
        },

        {
          name: 'agent10SpecializedDomain',
          type: 'group',
          label: 'Agent 10: Specialized Domain',
          fields: [
            {
              name: 'domainGrounding',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 地魂 - Grounds domain' },
            },
            {
              name: 'domainJudgment',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 智魂 - Domain judgment' },
            },
            {
              name: 'purposeApplication',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 命魂 - Applies purpose' },
            },
            {
              name: 'novelApproaches',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 創魂 - Novel approaches' },
            },
            {
              name: 'domainExecution',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 力魄 - Executes domain tasks' },
            },
            {
              name: 'taskSpeed',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 速魄 - Task speed' },
            },
            {
              name: 'patternNoticing',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 感魄 - Notices patterns' },
            },
            {
              name: 'integrityGuarding',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 守魄 - Guards integrity' },
            },
            {
              name: 'domainExpression',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 通魄 - Domain expression' },
            },
            {
              name: 'domainAdaptation',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 化魄 - Adapts domain approaches' },
            },
          ],
        },

        {
          name: 'agent11Monitor',
          type: 'group',
          label: 'Agent 11: Monitor (Self-observation)',
          fields: [
            {
              name: 'selfMonitoring',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 覺魂 - Self-monitors' },
            },
            {
              name: 'stableMonitoring',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 地魂 - Keeps stable' },
            },
            {
              name: 'resourceManagement',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 力魄 - Manages resources' },
            },
            {
              name: 'latencyMonitoring',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 速魄 - Latency mgmt' },
            },
            {
              name: 'signalDetection',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 感魄 - Signal detect' },
            },
            {
              name: 'systemSecurity',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 守魄 - System security' },
            },
            {
              name: 'resourceAdaptation',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 化魄 - Adapts resources' },
            },
          ],
        },

        {
          name: 'agent12Learning',
          type: 'group',
          label: 'Agent 12: Learning (Continuous Adaptation)',
          fields: [
            {
              name: 'meaningSeekingtype: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 天魂 - Seeks meaning in patterns' },
            },
            {
              name: 'realLearning',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 地魂 - Learns from real' },
            },
            {
              name: 'purposeLearning',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 命魂 - Adapts toward purpose' },
            },
            {
              name: 'judgmentLearning',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 智魂 - Learns judgment' },
            },
            {
              name: 'emotionalLearning',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 情魂 - Learns emotional patterns' },
            },
            {
              name: 'creativeLearning',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 創魂 - Learns creative patterns' },
            },
            {
              name: 'learningAwareness',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 覺魂 - Knows what to learn' },
            },
            {
              name: 'executionLearning',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 力魄 - Gets done' },
            },
            {
              name: 'perceptionLearning',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 感魄 - Learns what to notice' },
            },
            {
              name: 'learningProtection',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 守魄 - Guards learning' },
            },
            {
              name: 'adaptationEngine',
              type: 'number',
              min: 0,
              max: 1,
              admin: { description: 'From 化魄 - IS the adaptation engine' },
            },
          ],
        },
      ],
    },

    // Configuration Metadata
    {
      name: 'configurationVersion',
      type: 'number',
      required: true,
      defaultValue: 1,
      admin: {
        description: 'Version of this configuration (increments on each update)',
      },
    },
    {
      name: 'lastUpdated',
      type: 'date',
      required: true,
      defaultValue: () => new Date(),
      admin: {
        description: 'When was this configuration last updated?',
      },
    },
    {
      name: 'autoGenerated',
      type: 'checkbox',
      defaultValue: true,
      admin: {
        description: 'Was this configuration auto-generated from soul composition?',
      },
    },
    {
      name: 'notes',
      type: 'richText',
      admin: {
        description: 'Additional notes about this configuration',
      },
    },
  ],
}
